algoritmo "semnome"
// Função :
// Autor :
// Data : 26/2/2018
// Seção de Declarações 
var
turno:caractere
inicio

escreval("Qual turno você estuda ?(M/V/N)")
leia(turno)

se (turno = "M") entao
   escreval("Bom dia...")
senao
   se (turno = "V") entao
      escreval("Boa tarde...")
senao
      se (turno = "N") entao
         escreval("Boa Noite...")
senao
escreval("Dado Invalido")

fimse
fimse
fimse
fimalgoritmo
